"""
PHASE 1 — BACKTEST TYPES

SAFETY: SHADOW MODE ONLY
NO live execution paths
NO paper order submission

Type definitions for shadow backtesting simulator.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class PriceBar:
    """
    OHLCV price bar for backtesting.
    
    SAFETY: Read-only data structure
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    
    def __post_init__(self):
        """Validate price bar data."""
        if self.open <= 0 or self.high <= 0 or self.low <= 0 or self.close <= 0:
            raise ValueError("All prices must be positive")
        if self.low > self.high:
            raise ValueError("Low price cannot exceed high price")
        if self.volume < 0:
            raise ValueError("Volume cannot be negative")


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    SAFETY: SHADOW mode only - never triggers live execution
    
    Attributes:
        strategy_id: Unique identifier for the strategy
        timestamp: When the signal was generated
        symbol: Trading symbol (e.g., "NVDA", "BTC")
        side: "BUY" or "SELL"
        confidence: Signal confidence score (0.0 to 1.0)
        price: Price at which signal was generated (optional)
    """
    strategy_id: str
    timestamp: datetime
    symbol: str
    side: str  # "BUY" or "SELL"
    confidence: float
    price: Optional[float] = None
    
    def __post_init__(self):
        """Validate signal data."""
        if self.side.upper() not in ("BUY", "SELL"):
            raise ValueError(f"Side must be 'BUY' or 'SELL', got '{self.side}'")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be between 0.0 and 1.0, got {self.confidence}")
        if self.price is not None and self.price <= 0:
            raise ValueError(f"Price must be positive, got {self.price}")
